<nav>
    <div class="left-nav">
        <div class="logo">
            <img src="images/logo.png" alt="Logo" width="70" height="70">
        </div>
        <div class="dropdown">
            <button class="dropbtn">Select an Option!</button>
            <div class="dropdown-content">
                <a href="index.php">Home</a>
                <a href="pets.php">Pets</a>
                <a href="add.php">Add More</a>
                <a href="gallery.php">Gallery</a>
            </div>
        </div>
    </div>
    <div class="right-nav">
        <form class="form-inline">
            <div class="search">
                <input type="text" placeholder="Search">
                <button type="submit"><i class="fa fa-search"></i></button>
            </div>
        </form>
    </div>
</nav>
